export const menu=[{
    id:'home',
    description:'Home',
    href:'/',
    subMenu:[]
},
{
    id:'servicio',
    description:'Servicios',
    href:'/servicio',
    subMenu:[]
},
{
    id:'nosotros',
    description:'Sobre nosotros',
    href:'/aboutus',
    subMenu:[]
},
{
    id:'contacto',
    description:'Contacto',
    href:'/contact',
    subMenu:[]
},
{
    id:'reserva',
    description:'Reserva',
    href:'/reserve',
    subMenu:[]
}]